#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

sudo apt-get update

sudo apt-get install -y curl

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -

sudo apt-get install -y nodejs